spring:
  h2:
    console:
      enabled: true

  datasource:
    username: admin
    url: jdbc:mysql://springboot-database.cn3x5unw9erg.ap-northeast-2.rds.amazonaws.com:3306/myblog
    password: qweasd8770!

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.tutorial: debug
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK